from django.db import models


class Task(models.Model):
    """A unit of work generated from a task template for one engagement.

    ``engagement_id``, ``template_id``, ``assigned_to_id`` and ``created_by_id``
    are plain ids, not foreign keys: those rows live in other services'
    databases and this service must not join across that boundary.
    """

    class Status(models.TextChoices):
        NOT_STARTED = "NOT_STARTED", "Not Started"
        IN_PROGRESS = "IN_PROGRESS", "In Progress"
        WAITING_FOR_CLIENT = "WAITING_FOR_CLIENT", "Waiting for Client"
        READY_FOR_REVIEW = "READY_FOR_REVIEW", "Ready for Review"
        CHANGES_REQUESTED = "CHANGES_REQUESTED", "Changes Requested"
        COMPLETED = "COMPLETED", "Completed"

    class CreatorType(models.TextChoices):
        USER = "USER", "User"
        SYSTEM = "SYSTEM", "System"

    OPEN_STATUSES = frozenset(
        {
            Status.NOT_STARTED,
            Status.IN_PROGRESS,
            Status.WAITING_FOR_CLIENT,
            Status.READY_FOR_REVIEW,
            Status.CHANGES_REQUESTED,
        }
    )

    engagement_id = models.PositiveBigIntegerField()
    template_id = models.PositiveBigIntegerField()

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    assigned_to_id = models.PositiveBigIntegerField(null=True, blank=True)

    # NULL when the task was generated by the worker rather than a person.
    created_by_id = models.PositiveBigIntegerField(null=True, blank=True)
    created_by_type = models.CharField(
        max_length=10,
        choices=CreatorType.choices,
        default=CreatorType.USER,
    )

    due_date = models.DateField()

    status = models.CharField(
        max_length=30,
        choices=Status.choices,
        default=Status.NOT_STARTED,
    )

    completed_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["due_date", "id"]
        constraints = [
            # One task per template per engagement. This is what makes task
            # generation idempotent under at-least-once event delivery.
            models.UniqueConstraint(
                fields=["engagement_id", "template_id"],
                name="unique_task_per_engagement_template",
            ),
            models.CheckConstraint(
                condition=models.Q(created_by_type="SYSTEM")
                | models.Q(created_by_type="USER", created_by_id__isnull=False),
                name="user_created_tasks_have_a_creator",
            ),
        ]
        indexes = [
            # "My tasks", filtered by status.
            models.Index(fields=["assigned_to_id", "status"], name="task_assignee_status_idx"),
            # Dashboard counters: overdue / due today / by status.
            models.Index(fields=["status", "due_date"], name="task_status_due_idx"),
            models.Index(fields=["engagement_id"], name="task_engagement_idx"),
        ]

    @property
    def is_open(self) -> bool:
        return self.status in self.OPEN_STATUSES

    def __str__(self) -> str:
        return f"{self.title} [{self.status}]"


class TaskHistory(models.Model):
    """Append-only audit trail of every status change on a task."""

    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="history")

    from_status = models.CharField(max_length=30)
    to_status = models.CharField(max_length=30)

    changed_by_id = models.PositiveBigIntegerField()
    comment = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at", "id"]
        verbose_name_plural = "task history"
        indexes = [
            models.Index(fields=["task", "created_at"], name="task_history_created_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.task_id}: {self.from_status} -> {self.to_status}"
