# Generated by Django 6.1.1 on 2026-09-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_id', models.PositiveBigIntegerField()),
                ('template_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_to_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System')], default='USER', max_length=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_CLIENT', 'Waiting for Client'), ('READY_FOR_REVIEW', 'Ready for Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['assigned_to_id', 'status'], name='task_assignee_status_idx'), models.Index(fields=['status', 'due_date'], name='task_status_due_idx'), models.Index(fields=['engagement_id'], name='task_engagement_idx')],
                'constraints': [models.UniqueConstraint(fields=('engagement_id', 'template_id'), name='unique_task_per_engagement_template'), models.CheckConstraint(condition=models.Q(('created_by_type', 'SYSTEM'), models.Q(('created_by_id__isnull', False), ('created_by_type', 'USER')), _connector='OR'), name='user_created_tasks_have_a_creator')],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_by_id', models.PositiveBigIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'task history',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='task_history_created_idx')],
            },
        ),
    ]
