# Generated by Django 6.1.1 on 2026-09-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.client')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='services.servicetype')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'service_type', 'period_start'], name='engagements_client__0b931a_idx'), models.Index(fields=['period_start', 'period_end'], name='engagements_period__a9b35c_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'service_type', 'period_start', 'period_end'), name='unique_client_service_period')],
            },
        ),
    ]
