# Generated by Django 6.1.1 on 2026-09-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='ONE_TIME', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('frequency', 'ONE_TIME'), ('is_recurring', False)), models.Q(models.Q(('frequency', 'ONE_TIME'), _negated=True), ('is_recurring', True)), _connector='OR'), name='recurring_flag_matches_frequency')],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('default_due_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='services.servicetype')),
            ],
            options={
                'ordering': ['service_type_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('service_type', 'sequence'), name='unique_template_sequence_per_service')],
            },
        ),
    ]
